name: searchify
description: for searchiing all in flutter and dart and in the world also with 3 method lineary,binary and jump method
version: 1.0.0
repository: https://github.com/Jamshidmirzo/searchify
homepage: https://jamshids-portfolio.netlify.app

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
