name: searchify
description: A starting point for Dart libraries or applications for searching all in dart file and in the world.
version: 1.0.0
repository: https://github.com/Jamshidmirzo/searchify
homepage: https://jamshids-portfolio.netlify.app

environment:
  sdk: ^3.4.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
